# -*- coding: utf-8 -*-
import unittest
from estnltk.clausesegmenter import ClauseSegmenter
from pprint import pprint


class ClauseSegmenterTest(unittest.TestCase):
    
    def test_arno(self):
        segmenter = ClauseSegmenter()
        segmented = segmenter(self.arno_document())
        self.assertDictEqual(segmented, self.arno_segmented())
        
    def arno_document(self):
        return {'end': 62,
                'paragraphs': [{'end': 62,
                                'rel_end': 62,
                                'rel_start': 0,
                                'sentences': [{'end': 62,
                                                'rel_end': 62,
                                                'rel_start': 0,
                                                'start': 0,
                                                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud',
                                                'words': [{'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'kui',
                                                                        'lemma_tokens': [u'kui'],
                                                                        'partofspeech': u'D',
                                                                        'root': u'kui'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'kui',
                                                                        'lemma_tokens': [u'kui'],
                                                                        'partofspeech': u'J',
                                                                        'root': u'kui'}],
                                                        'end': 3,
                                                        'rel_end': 3,
                                                        'rel_start': 0,
                                                        'start': 0,
                                                        'text': u'Kui'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg g',
                                                                        'lemma': u'Arno',
                                                                        'lemma_tokens': [u'Arno'],
                                                                        'partofspeech': u'H',
                                                                        'root': u'Arno'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'Arno',
                                                                        'lemma_tokens': [u'Arno'],
                                                                        'partofspeech': u'H',
                                                                        'root': u'Arno'}],
                                                        'end': 8,
                                                        'rel_end': 8,
                                                        'rel_start': 4,
                                                        'start': 4,
                                                        'text': u'Arno'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'i',
                                                                        'form': u's',
                                                                        'lemma': u'ole',
                                                                        'lemma_tokens': [u'ole'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'ole'}],
                                                        'end': 12,
                                                        'rel_end': 12,
                                                        'rel_start': 9,
                                                        'start': 9,
                                                        'text': u'oli'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'ga',
                                                                        'form': u'sg kom',
                                                                        'lemma': u'isa',
                                                                        'lemma_tokens': [u'isa'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'isa'}],
                                                        'end': 18,
                                                        'rel_end': 18,
                                                        'rel_start': 13,
                                                        'start': 13,
                                                        'text': u'isaga'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'adt',
                                                                        'lemma': u'koolimaja',
                                                                        'lemma_tokens': [u'kooli',
                                                                                        u'maja'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'kool]i_maja'}],
                                                        'end': 29,
                                                        'rel_end': 29,
                                                        'rel_start': 19,
                                                        'start': 19,
                                                        'text': u'koolimajja'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'nud',
                                                                        'form': u'nud',
                                                                        'lemma': u'j\xf5ud',
                                                                        'lemma_tokens': [u'j\xf5ud'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'j<\xf5ud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'j\xf5udnu',
                                                                        'lemma_tokens': [u'j\xf5udnu'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'j<\xf5ud=nu'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'}],
                                                        'end': 37,
                                                        'rel_end': 37,
                                                        'rel_start': 30,
                                                        'start': 30,
                                                        'text': u'j\xf5udnud'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'',
                                                                        'form': u'',
                                                                        'lemma': u',',
                                                                        'lemma_tokens': [u','],
                                                                        'partofspeech': u'Z',
                                                                        'root': u','}],
                                                        'end': 38,
                                                        'rel_end': 38,
                                                        'rel_start': 37,
                                                        'start': 37,
                                                        'text': u','},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'id',
                                                                        'form': u'sid',
                                                                        'lemma': u'ole',
                                                                        'lemma_tokens': [u'ole'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'ole'}],
                                                        'end': 43,
                                                        'rel_end': 43,
                                                        'rel_start': 39,
                                                        'start': 39,
                                                        'text': u'olid'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'tund',
                                                                        'lemma_tokens': [u'tund'],
                                                                        'partofspeech': u'S',
                                                                        'root': u't<un]d'}],
                                                        'end': 50,
                                                        'rel_end': 50,
                                                        'rel_start': 44,
                                                        'start': 44,
                                                        'text': u'tunnid'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'juba',
                                                                        'lemma_tokens': [u'juba'],
                                                                        'partofspeech': u'D',
                                                                        'root': u'juba'}],
                                                        'end': 55,
                                                        'rel_end': 55,
                                                        'rel_start': 51,
                                                        'start': 51,
                                                        'text': u'juba'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'nud',
                                                                        'form': u'nud',
                                                                        'lemma': u'alga',
                                                                        'lemma_tokens': [u'alga'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'<alga'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'alanu',
                                                                        'lemma_tokens': [u'alanu'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'ala=nu'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'}],
                                                        'end': 62,
                                                        'rel_end': 62,
                                                        'rel_start': 56,
                                                        'start': 56,
                                                        'text': u'alanud'}]}],
                                'start': 0,
                                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud'}],
                'rel_end': 62,
                'rel_start': 0,
                'start': 0,
                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud'}
                
    def arno_segmented(self):
        return {'end': 62,
                'paragraphs': [{'end': 62,
                                'rel_end': 62,
                                'rel_start': 0,
                                'sentences': [{'end': 62,
                                                'rel_end': 62,
                                                'rel_start': 0,
                                                'start': 0,
                                                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud',
                                                'words': [{'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'kui',
                                                                        'lemma_tokens': [u'kui'],
                                                                        'partofspeech': u'D',
                                                                        'root': u'kui'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'kui',
                                                                        'lemma_tokens': [u'kui'],
                                                                        'partofspeech': u'J',
                                                                        'root': u'kui'}],
                                                        'end': 3,
                                                        'rel_end': 3,
                                                        'rel_start': 0,
                                                        'start': 0,
                                                        'text': u'Kui'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg g',
                                                                        'lemma': u'Arno',
                                                                        'lemma_tokens': [u'Arno'],
                                                                        'partofspeech': u'H',
                                                                        'root': u'Arno'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'Arno',
                                                                        'lemma_tokens': [u'Arno'],
                                                                        'partofspeech': u'H',
                                                                        'root': u'Arno'}],
                                                        'end': 8,
                                                        'rel_end': 8,
                                                        'rel_start': 4,
                                                        'start': 4,
                                                        'text': u'Arno'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'i',
                                                                        'form': u's',
                                                                        'lemma': u'ole',
                                                                        'lemma_tokens': [u'ole'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'ole'}],
                                                        'end': 12,
                                                        'rel_end': 12,
                                                        'rel_start': 9,
                                                        'start': 9,
                                                        'text': u'oli'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'ga',
                                                                        'form': u'sg kom',
                                                                        'lemma': u'isa',
                                                                        'lemma_tokens': [u'isa'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'isa'}],
                                                        'end': 18,
                                                        'rel_end': 18,
                                                        'rel_start': 13,
                                                        'start': 13,
                                                        'text': u'isaga'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'adt',
                                                                        'lemma': u'koolimaja',
                                                                        'lemma_tokens': [u'kooli',
                                                                                        u'maja'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'kool]i_maja'}],
                                                        'end': 29,
                                                        'rel_end': 29,
                                                        'rel_start': 19,
                                                        'start': 19,
                                                        'text': u'koolimajja'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'nud',
                                                                        'form': u'nud',
                                                                        'lemma': u'j\xf5ud',
                                                                        'lemma_tokens': [u'j\xf5ud'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'j<\xf5ud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'j\xf5udnu',
                                                                        'lemma_tokens': [u'j\xf5udnu'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'j<\xf5ud=nu'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'j\xf5udnud',
                                                                        'lemma_tokens': [u'j\xf5udnud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'j<\xf5ud=nud'}],
                                                        'end': 37,
                                                        'rel_end': 37,
                                                        'rel_start': 30,
                                                        'start': 30,
                                                        'text': u'j\xf5udnud'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'',
                                                                        'form': u'',
                                                                        'lemma': u',',
                                                                        'lemma_tokens': [u','],
                                                                        'partofspeech': u'Z',
                                                                        'root': u','}],
                                                        'clauseAnnotation': [u'KINDEL_PIIR'],
                                                        'end': 38,
                                                        'rel_end': 38,
                                                        'rel_start': 37,
                                                        'start': 37,
                                                        'text': u','},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'id',
                                                                        'form': u'sid',
                                                                        'lemma': u'ole',
                                                                        'lemma_tokens': [u'ole'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'ole'}],
                                                        'end': 43,
                                                        'rel_end': 43,
                                                        'rel_start': 39,
                                                        'start': 39,
                                                        'text': u'olid'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'tund',
                                                                        'lemma_tokens': [u'tund'],
                                                                        'partofspeech': u'S',
                                                                        'root': u't<un]d'}],
                                                        'end': 50,
                                                        'rel_end': 50,
                                                        'rel_start': 44,
                                                        'start': 44,
                                                        'text': u'tunnid'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'juba',
                                                                        'lemma_tokens': [u'juba'],
                                                                        'partofspeech': u'D',
                                                                        'root': u'juba'}],
                                                        'end': 55,
                                                        'rel_end': 55,
                                                        'rel_start': 51,
                                                        'start': 51,
                                                        'text': u'juba'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'nud',
                                                                        'form': u'nud',
                                                                        'lemma': u'alga',
                                                                        'lemma_tokens': [u'alga'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'<alga'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'alanu',
                                                                        'lemma_tokens': [u'alanu'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'ala=nu'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'},
                                                                        {'clitic': u'',
                                                                        'ending': u'd',
                                                                        'form': u'pl n',
                                                                        'lemma': u'alanud',
                                                                        'lemma_tokens': [u'alanud'],
                                                                        'partofspeech': u'A',
                                                                        'root': u'ala=nud'}],
                                                        'end': 62,
                                                        'rel_end': 62,
                                                        'rel_start': 56,
                                                        'start': 56,
                                                        'text': u'alanud'}]}],
                                'start': 0,
                                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud'}],
                'rel_end': 62,
                'rel_start': 0,
                'start': 0,
                'text': u'Kui Arno oli isaga koolimajja j\xf5udnud, olid tunnid juba alanud'}

                
if __name__ == '__main__':
    unittest.main()
