# -*- coding: utf-8 -*-

import unittest
from estnltk.morf import PyVabamorfAnalyzer

class PyVabamorfAnalyzerTest(unittest.TestCase):
    
    def test_morphoanalysis(self):
        analyzer = PyVabamorfAnalyzer()
        analyzed = analyzer(self.simple_document())
        self.assertDictEqual(analyzed, self.simple_morphoanalyzed())
    
    def simple_document(self):
        return {'end': 13,
                'paragraphs': [{'end': 13,
                                'rel_end': 13,
                                'rel_start': 0,
                                'sentences': [{'end': 13,
                                                'rel_end': 13,
                                                'rel_start': 0,
                                                'start': 0,
                                                'text': u'Mees oli mees',
                                                'words': [{'end': 4,
                                                        'rel_end': 4,
                                                        'rel_start': 0,
                                                        'start': 0,
                                                        'text': u'Mees'},
                                                        {'end': 8,
                                                        'rel_end': 8,
                                                        'rel_start': 5,
                                                        'start': 5,
                                                        'text': u'oli'},
                                                        {'end': 13,
                                                        'rel_end': 13,
                                                        'rel_start': 9,
                                                        'start': 9,
                                                        'text': u'mees'}]}],
                                'start': 0,
                                'text': u'Mees oli mees'}],
                'rel_end': 13,
                'rel_start': 0,
                'start': 0,
                'text': u'Mees oli mees'}

    def simple_morphoanalyzed(self):
        return {'end': 13,
                'paragraphs': [{'end': 13,
                                'rel_end': 13,
                                'rel_start': 0,
                                'sentences': [{'end': 13,
                                                'rel_end': 13,
                                                'rel_start': 0,
                                                'start': 0,
                                                'text': u'Mees oli mees',
                                                'words': [{'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'mees',
                                                                        'lemma_tokens': [u'mees'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'm<ees'},
                                                                        {'clitic': u'',
                                                                        'ending': u's',
                                                                        'form': u'sg in',
                                                                        'lemma': u'mesi',
                                                                        'lemma_tokens': [u'mesi'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'mes]i'}],
                                                        'end': 4,
                                                        'rel_end': 4,
                                                        'rel_start': 0,
                                                        'start': 0,
                                                        'text': u'Mees'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'i',
                                                                        'form': u's',
                                                                        'lemma': u'ole',
                                                                        'lemma_tokens': [u'ole'],
                                                                        'partofspeech': u'V',
                                                                        'root': u'ole'}],
                                                        'end': 8,
                                                        'rel_end': 8,
                                                        'rel_start': 5,
                                                        'start': 5,
                                                        'text': u'oli'},
                                                        {'analysis': [{'clitic': u'',
                                                                        'ending': u'0',
                                                                        'form': u'sg n',
                                                                        'lemma': u'mees',
                                                                        'lemma_tokens': [u'mees'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'm<ees'},
                                                                        {'clitic': u'',
                                                                        'ending': u's',
                                                                        'form': u'sg in',
                                                                        'lemma': u'mesi',
                                                                        'lemma_tokens': [u'mesi'],
                                                                        'partofspeech': u'S',
                                                                        'root': u'mes]i'}],
                                                        'end': 13,
                                                        'rel_end': 13,
                                                        'rel_start': 9,
                                                        'start': 9,
                                                        'text': u'mees'}]}],
                                'start': 0,
                                'text': u'Mees oli mees'}],
                'rel_end': 13,
                'rel_start': 0,
                'start': 0,
                'text': u'Mees oli mees'}

if __name__ == '__main__':
    unittest.main()

