from collocation_net.base_collocation_net import BaseCollocationNet
from collocation_net.noun_adjective_collocation_net import NounAdjectiveCollocationNet
from collocation_net.subject_verb_collocation_net import SubjectVerbCollocationNet
from collocation_net.object_verb_collocation_net import ObjectVerbCollocationNet
from collocation_net.verb_subject_collocation_net import VerbSubjectCollocationNet
from collocation_net.verb_object_collocation_net import VerbObjectCollocationNet
