from collocation_net.base_collocation_net import BaseCollocationNet
from collocation_net.noun_adjective_collocation_net import NounAdjectiveCollocationNet
from collocation_net.subject_verb_collocation_net import SubjectVerbCollocationNet
from verb_object_collocation_net import VerbObjectCollocationNet
