from estnltk import Text
from estnltk.converters import layer_to_dict
from estnltk.taggers import VislTagger


visl_dict = {'_base': 'words',
             'ambiguous': True,
             'attributes': ('id',
              'form',
              'lemma',
              'upostag',
              'xpostag',
              'feats',
              'head',
              'deprel',
              'deps',
              'misc'),
             'enveloping': None,
             'name': 'visl',
             'parent': 'words',
             'spans': [[{'_index_': 0,
                'deprel': '@ADVL',
                'deps': '_',
                'end': 9,
                'feats': 'rel|sg|tr|cap',
                'form': 'Milliseks',
                'head': '2',
                'id': '1',
                'lemma': 'milline',
                'misc': '_',
                'start': 0,
                'upostag': 'P',
                'xpostag': 'P'}],
              [{'_index_': 1,
                'deprel': '@FMV',
                'deps': '_',
                'end': 17,
                'feats': 'main|indic|pres|ps3|sg|ps|af',
                'form': 'kujuneb',
                'head': '0',
                'id': '2',
                'lemma': 'kujune',
                'misc': '_',
                'start': 10,
                'upostag': 'V',
                'xpostag': 'V'}],
              [{'_index_': 2,
                'deprel': '@NN>',
                'deps': '_',
                'end': 28,
                'feats': 'com|sg|gen|cap',
                'form': 'Riigikassa',
                'head': '5',
                'id': '3',
                'lemma': 'riigi_kassa',
                'misc': '_',
                'start': 18,
                'upostag': 'S',
                'xpostag': 'S'}],
              [{'_index_': 3,
                'deprel': '@J',
                'deps': '_',
                'end': 31,
                'feats': 'crd',
                'form': 'ja',
                'head': '5',
                'id': '4',
                'lemma': 'ja',
                'misc': '_',
                'start': 29,
                'upostag': 'J',
                'xpostag': 'J'}],
              [{'_index_': 4,
                'deprel': '@NN>',
                'deps': '_',
                'end': 41,
                'feats': 'prop|sg|gen|cap',
                'form': 'Ühispanga',
                'head': '6',
                'id': '5',
                'lemma': 'Ühis_pank',
                'misc': '_',
                'start': 32,
                'upostag': 'S',
                'xpostag': 'S'}],
              [{'_index_': 5,
                'deprel': '@SUBJ',
                'deps': '_',
                'end': 50,
                'feats': 'com|sg|nom',
                'form': 'vahekord',
                'head': '2',
                'id': '6',
                'lemma': 'vahe_kord',
                'misc': '_',
                'start': 42,
                'upostag': 'S',
                'xpostag': 'S'}],
              [{'_index_': 6,
                'deprel': 'xxx',
                'deps': '_',
                'end': 52,
                'feats': 'Int|CLB',
                'form': '?',
                'head': '6',
                'id': '7',
                'lemma': '?',
                'misc': '_',
                'start': 51,
                'upostag': 'Z',
                'xpostag': 'Z'}]]}


def test_visl_tagger():
    text = Text('Milliseks kujuneb Riigikassa ja Ühispanga vahekord ?').tag_layer(['morph_extended'])

    tagger = VislTagger()
    tagger.tag(text)
    result = layer_to_dict(layer=text.visl, text=text)
    assert visl_dict == result
