from pprint import pformat
from typing import List
from os import path

from estnltk.text import Text
from estnltk.taggers import Tagger
from estnltk.converters import export_dict, import_dict
from estnltk.converters import export_json, import_json


template = """# this test file is automatically generated by tagger_test_maker.py

from estnltk.converters import import_dict
{tagger_creation}
input_text_dict = \\
{text_dict_str}

expected_text_dict = \\
{expected_text_dict}


expected_layer_text = {expected_layer_text}

expected_text = import_dict(expected_text_dict)

input_text = import_dict(input_text_dict)
result = tagger.tag(input_text)
diff = expected_text.diff(result)


def test_basic():
    assert expected_layer_text == result[tagger.output_layer].text, {annotation!r}


def test_complete():
    assert not diff, diff + '\\n' + {annotation!r}
"""


def make_tagger_test(tagger_creation: str,
                     text: Text,
                     expected_layer_text: List[str],
                     test_file: str,
                     annotation: str,
                     overwrite: bool=False):
    if not overwrite and path.exists(test_file):
        print("File '" + path.split(test_file)[-1] + "' already exists. Use 'overwrite=True' to overwrite.")
        return

    scope = {}
    exec(tagger_creation, scope)
    tagger = scope['tagger']

    text_dict_str = pformat(export_dict(text))
    assert text == import_dict(eval(text_dict_str)), "can't export input text"
    expected_text = tagger.tag(text)
    expected_layer_text = list(expected_layer_text)
    assert expected_layer_text == expected_text[tagger.output_layer].text,\
        str(expected_layer_text) + ' != ' + str(expected_text[tagger.output_layer].text)
    expected_text_dict_str = pformat(export_dict(expected_text))
    assert expected_text == import_dict(eval(expected_text_dict_str)), "can't export expected text"
    file_contents = template.format(text_dict_str=text_dict_str,
                                    tagger_creation=tagger_creation,
                                    expected_text_dict=expected_text_dict_str,
                                    expected_layer_text=expected_layer_text,
                                    annotation=annotation)
    with open(test_file, 'w') as out_f:
        out_f.write(file_contents)
        print("Created '" + path.split(test_file)[-1] + "'.")


def make_tagger_test_files(
                           input_text: Text,
                           tagger: Tagger,
                           expected_layer_text: List[str],
                           input_text_file: str,
                           expected_text_file: str,
                           overwrite: bool=False
                           ):
    if not overwrite and path.exists(input_text_file):
        print("File '" + path.split(input_text_file)[-1] + "' already exists. Use 'overwrite=True' to overwrite.")
        return
    if not overwrite and path.exists(expected_text_file):
        print("File '" + path.split(expected_text_file)[-1] + "' already exists. Use 'overwrite=True' to overwrite.")
        return

    export_json(input_text, input_text_file)
    print("Created '" + path.split(input_text_file)[-1] + "'.")

    input_text_copy = import_json(file=input_text_file)
    assert input_text == input_text_copy, "can't export input text to json"

    expected_text = tagger.tag(input_text_copy)

    expected_layer_text = list(expected_layer_text)
    assert expected_layer_text == expected_text[tagger.output_layer].text,\
        str(expected_layer_text) + ' != ' + str(expected_text[tagger.output_layer].text)

    export_json(expected_text, expected_text_file)
    print("Created '" + path.split(expected_text_file)[-1] + "'.")


def test_tagger(tagger, input_text_file, expected_text_file, annotation=''):
    input_text = import_json(file=input_text_file)
    expected_text = import_json(file=expected_text_file)
    result = tagger.tag(input_text)
    diff = expected_text.diff(result)
    assert not diff, diff + '\n' + annotation
