from estnltk_core.layer.attribute_list.ambiguous_attribute_tuple_list import AmbiguousAttributeTupleList
from estnltk_core.layer.attribute_list.ambiguous_attribute_list import AmbiguousAttributeList
from estnltk_core.layer.attribute_list.attribute_tuple_list import AttributeTupleList
from estnltk_core.layer.attribute_list.attribute_list import AttributeList
