{% set version = "1.7.4" %}

package:
  name: estnltk_core
  version: {{ version }}

source:
    path: ../../estnltk_core

build:
 noarch: python
 number: 0
 script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python 
    - regex >=2015.11.22
    - networkx
    - pandas
    - IPython
    - packaging

about:
  home: https://github.com/estnltk/estnltk
  license: 'Dual License: GPL-2.0 OR Apache-2.0'
  summary: 'EstNLTK core - basic data structures and components of the EstNLTK library'