{% set data = load_setup_py_data() %}

package:
  name: estnltk-core
  version: {{ data.get('version')  }}

source:
    path: ../../

build:
 noarch: python
 number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
 string: {{ environ.get('PY_VER', '') }}

requirements:
  build:
    - python 
    - regex >=2015.11.22
    - networkx
    - pandas

  run:
    - python 
    - regex >=2015.11.22
    - networkx
    - pandas
    - IPython

about:
  home: https://github.com/estnltk/estnltk
  license: GPLv2
  summary: 'EstNLTK core - basic data structures and components of the EstNLTK library'