{% set data = load_setup_py_data() %}

package:
  name: estnltk_core
  version: {{ data.get('version')  }}

source:
    path: ../../estnltk_core

build:
 noarch: python
 number: 0

requirements:
  build:
    - python 
    - regex >=2015.11.22
    - networkx
    - pandas
    - packaging

  run:
    - python 
    - regex >=2015.11.22
    - networkx
    - pandas
    - IPython
    - packaging

about:
  home: https://github.com/estnltk/estnltk
  license: 'Dual License: GPL-2.0 OR Apache-2.0'
  summary: 'EstNLTK core - basic data structures and components of the EstNLTK library'