vocabulary = [
{'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': '((K|k)olesteroo?l|KOLESTEROOL|(K|k)olester|Chol|(K|k)olest?|kol|chol|CHol|CHL|KOL|Kol|cHOL|CHOL|ÜK|ük|Ük)',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'kolesterool'},

{'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': '(((S|s)iinus)?r.tm(iline|ilised)?|[Ff]rekv?(ents)?|fr\.?|Fr|BPM|bpm|SR|SLS|FR|HR|(P|p)ulss(i)?|Ps)(\s*[xX]\s*)?',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'pulss'},

{ 'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': '((([Ss]ünni)|([Kk]eha))?(p|P)ikkus|PIKKUS|pikkusega|[^A-Z]SP|sp|pikk|kasv|Kasv)',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'pikkus'},

{ 'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': '(psa|Psa|S-PSA|[Pp]rostataspetsiifiline\s*antigeen(\s*seerumis)?|PSA|(S\s*,\s*P-)?(\s*PSA))',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'psa'},

{'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': '((((K|k)eha)|((S|s)ünni))?(K|k)aal(uga)?|kAAL|SK|Sk|[^a-z]sk|KAAL|SM|[Ss]/k|(K|k)aalu(ga|nud|b|s))',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'kaal'},

{ 'grammar_symbol': 'MO',
 'regex_type': 'measurement_object',
 '_regex_pattern_': 'ALAT',
 '_group_': 0,
 '_priority_': -1,
 '_validator_': lambda m: True,
 'value': 'alat'}
]