import regex as re

vocabulary = [
{'grammar_symbol': 'UNIT',
 'regex_type': 'psa_unit',
 '_regex_pattern_': r'(ng/mL|ng/L|mk(ro)?g/[Ll]|ng/\s*ml|ng7ml|mg/ml|ng\ml|ng/l|ug/L|ngIml|µg/L|mcg/L|ng/mg)',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': lambda m: re.search('(ng/mL|ng/L|mk(ro)?g/[Ll]|ng/\s*ml|ng7ml|mg/ml|ng\ml|ng/l|ug/L|ngIml|µg/L|mcg/L|ng/mg)', m.group(0)).group(0)},

{'grammar_symbol': 'UNIT',
 'regex_type': 'time_unit',
 '_regex_pattern_': r'(a[. ]|k[. ]|aasta|kuu|nädal|[Xx]|kord|min|msek|ms|)',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{ 'grammar_symbol': 'UNIT',
 'regex_type': 'chol_unit',
 '_regex_pattern_': r'((mmoo?l?i?|mm|MMOL|mol)(\s*[-/]\s*(L|l))?|MMOL/L)',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{'grammar_symbol': 'UNIT',
 'regex_type': 'pulss_unit',
 '_regex_pattern_': r"(((l|x|X|lööki))\s*/?\s*(1\s*)?min(utis)?)|/min|x[\'´`]|bpm|BPM",
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{ 'grammar_symbol': 'UNIT',
 'regex_type': 'alat_unit',
 '_regex_pattern_': r'U/L',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{'grammar_symbol': 'UNIT',
 'regex_type': 'pikkus_unit',
 '_regex_pattern_': r'(cm|Cm|sm|SM|CM|m)',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{'grammar_symbol': 'UNIT',
 'regex_type': 'kaal_unit',
 '_regex_pattern_': r'(gramm|kg|mg|kG|gr|g|KG|G)',
 '_group_': 0,
 '_priority_': 1,
 '_validator_': lambda m: True,
 'value': 'x'},

{'grammar_symbol': 'UNIT',
 'regex_type': 'rubbish',
 '_regex_pattern_': r'(mg|mkg|tsentiil|prts|(pro)?tsentiil|pt|mm)($|[^a-zA-Z]])',
 '_group_': 0,
 '_priority_': -2,
 '_validator_':  lambda m: True,
 'value': 'not_pikkus_unit'},
]
