from estnltk.web_taggers.v01.web_tagger import WebTagger, WebRelationTagger
from estnltk.web_taggers.v01.batch_processing_web_tagger import BatchProcessingWebTagger
from estnltk.web_taggers.v01.batch_processing_web_relation_tagger import BatchProcessingWebRelationTagger
from estnltk.web_taggers.v01.neural_morph_disamb_web_tagger import NeuralMorphDisambWebTagger
from estnltk.web_taggers.v01.vabamorf_web_tagger import VabamorfWebTagger
from estnltk.web_taggers.v01.bert_embeddings_web_tagger import BertEmbeddingsWebTagger
from estnltk.web_taggers.v01.stanza_syntax_web_tagger import StanzaSyntaxWebTagger
from estnltk.web_taggers.v01.stanza_syntax_ensemble_web_tagger import StanzaSyntaxEnsembleWebTagger
from estnltk.web_taggers.v01.coreference_v1_web_tagger import CoreferenceV1WebTagger

from estnltk.web_taggers.ner.ner_web_tagger import NerWebTagger
from estnltk.web_taggers.grammar_corrector.grammar_corrector_web_tagger import GrammarCorrectorWebTagger