{% set data = load_setup_py_data() %}


package:
  name: estnltk
  version: {{ data.get('version')  }}

source:
    path: ../..

build:
 number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
 string: {{ environ.get('PY_VER', '') }}


requirements:
  build:
    - python 
    - swig ==3.0.12
    - six >=1.9.0
    - nltk >=3.0.4
    - regex >=2015.11.22
    - pandas
    - python-crfsuite >=0.8.4
    - cached-property >=1.2.0
    - beautifulsoup4 >=4.4.0
    - html5lib
    - networkx
    - lxml
  run:
    - python
    - six >=1.9.0
    - nltk >=3.0.4
    - regex >=2015.11.22
    - pandas
    - python-crfsuite >=0.8.4
    - cached-property >=1.2.0
    - beautifulsoup4 >=4.4.0
    - html5lib
    - networkx
    - lxml
    - tqdm
    - IPython
    - requests
    - matplotlib

about:
  home: https://github.com/estnltk/estnltk
  license: GPLv2
  summary: 'Estnltk open source tools for Estonian natural language processing'
