from collections import OrderedDict

from estnltk import Text
from estnltk.common import PACKAGE_PATH

from estnltk.taggers.standard.morph_analysis.ud_morf import UDMorphConverter

from estnltk.converters import layer_to_dict
from estnltk.converters import dict_to_layer

import os, os.path

# -------------------------------------------------------------------------------

def test_ud_morph_converter_smoke():
    # Smoke test for UDMorphConverter
    
    # Case 1 
    text = Text('Ilus suur kass lesis kollasel diivanil.')
    # Tag required layers
    text.tag_layer(['words', 'sentences', 'morph_analysis'])
    # Convert morph categories to UD
    ud_converter = UDMorphConverter( remove_connegatives=True, 
                                     generate_num_cases=True )
    assert ud_converter.output_layer == 'ud_morph_analysis'
    ud_converter.tag( text )
    assert ud_converter.output_layer in text.layers
    
    expected_ud_morph_layer_dict_1 = \
        {'ambiguous': True,
         'attributes': ('id', 'lemma', 'upostag', 'xpostag', 'feats', 'misc'),
         'enveloping': None,
         'meta': {},
         'name': 'ud_morph_analysis',
         'parent': 'morph_analysis',
         'secondary_attributes': (),
         'serialisation_module': None,
         'spans': [{'annotations': [{'feats': OrderedDict([('Degree', 'Pos'),
                                                           ('Number', 'Sing'),
                                                           ('Case', 'Nom')]),
                                     'id': 1,
                                     'lemma': 'ilus',
                                     'misc': '',
                                     'upostag': 'ADJ',
                                     'xpostag': 'A'}],
                    'base_span': (0, 4)},
                   {'annotations': [{'feats': OrderedDict([('Degree', 'Pos'),
                                                           ('Number', 'Sing'),
                                                           ('Case', 'Nom')]),
                                     'id': 2,
                                     'lemma': 'suur',
                                     'misc': '',
                                     'upostag': 'ADJ',
                                     'xpostag': 'A'}],
                    'base_span': (5, 9)},
                   {'annotations': [{'feats': OrderedDict([('Number', 'Sing'),
                                                           ('Case', 'Nom')]),
                                     'id': 3,
                                     'lemma': 'kass',
                                     'misc': '',
                                     'upostag': 'NOUN',
                                     'xpostag': 'S'}],
                    'base_span': (10, 14)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Past'),
                                                           ('Mood', 'Ind'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Number', 'Sing'),
                                                           ('Person', '3')]),
                                     'id': 4,
                                     'lemma': 'lesima',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'}],
                    'base_span': (15, 20)},
                   {'annotations': [{'feats': OrderedDict([('Degree', 'Pos'),
                                                           ('Number', 'Sing'),
                                                           ('Case', 'Ade')]),
                                     'id': 5,
                                     'lemma': 'kollane',
                                     'misc': '',
                                     'upostag': 'ADJ',
                                     'xpostag': 'A'}],
                    'base_span': (21, 29)},
                   {'annotations': [{'feats': OrderedDict([('Number', 'Sing'),
                                                           ('Case', 'Ade')]),
                                     'id': 6,
                                     'lemma': 'diivan',
                                     'misc': '',
                                     'upostag': 'NOUN',
                                     'xpostag': 'S'}],
                    'base_span': (30, 38)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 7,
                                     'lemma': '.',
                                     'misc': '',
                                     'upostag': 'PUNCT',
                                     'xpostag': 'Z'}],
                    'base_span': (38, 39)}]}
    assert expected_ud_morph_layer_dict_1 == layer_to_dict( text['ud_morph_analysis'] )
    
    #from pprint import pprint
    #pprint( layer_to_dict(text['ud_morph_analysis']) )

# -------------------------------------------------------------------------------

def test_ud_morph_converter_remove_connegatives():
    # Test that redundant connegative annotations are removed if possible.
    text = Text('Vist peaks tegutsema. Mingem edasi. Las jääb nii. Ei elata.')
    # Tag required layers
    text.tag_layer(['words', 'sentences', 'morph_analysis'])
    # Convert morph categories to UD
    ud_converter = UDMorphConverter( remove_connegatives=True )
    ud_converter.tag( text )
    
    expected_ud_morph_layer_dict = \
        {'ambiguous': True,
         'attributes': ('id', 'lemma', 'upostag', 'xpostag', 'feats', 'misc'),
         'enveloping': None,
         'meta': {},
         'name': 'ud_morph_analysis',
         'parent': 'morph_analysis',
         'secondary_attributes': (),
         'serialisation_module': None,
         'spans': [{'annotations': [{'feats': OrderedDict(),
                                     'id': 1,
                                     'lemma': 'vist',
                                     'misc': '',
                                     'upostag': 'ADV',
                                     'xpostag': 'D'}],
                    'base_span': (0, 4)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Cnd'),
                                                           ('VerbForm', 'Fin')]),
                                     'id': 2,
                                     'lemma': 'pidama',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'},
                                    {'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Cnd'),
                                                           ('VerbForm', 'Fin')]),
                                     'id': 2,
                                     'lemma': 'pidama',
                                     'misc': '',
                                     'upostag': 'AUX',
                                     'xpostag': 'V'}],
                    'base_span': (5, 10)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('VerbForm', 'Sup'),
                                                           ('Case', 'Ill')]),
                                     'id': 3,
                                     'lemma': 'tegutsema',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'}],
                    'base_span': (11, 20)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 4,
                                     'lemma': '.',
                                     'misc': '',
                                     'upostag': 'PUNCT',
                                     'xpostag': 'Z'}],
                    'base_span': (20, 21)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Imp'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Number', 'Plur'),
                                                           ('Person', '1')]),
                                     'id': 1,
                                     'lemma': 'minema',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'}],
                    'base_span': (22, 28)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 2,
                                     'lemma': 'edasi',
                                     'misc': '',
                                     'upostag': 'ADV',
                                     'xpostag': 'D'}],
                    'base_span': (29, 34)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 3,
                                     'lemma': '.',
                                     'misc': '',
                                     'upostag': 'PUNCT',
                                     'xpostag': 'Z'}],
                    'base_span': (34, 35)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 1,
                                     'lemma': 'las',
                                     'misc': '',
                                     'upostag': 'ADV',
                                     'xpostag': 'D'}],
                    'base_span': (36, 39)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Ind'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Number', 'Sing'),
                                                           ('Person', '3')]),
                                     'id': 2,
                                     'lemma': 'jääma',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'}],
                    'base_span': (40, 44)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 3,
                                     'lemma': 'nii',
                                     'misc': '',
                                     'upostag': 'ADV',
                                     'xpostag': 'D'}],
                    'base_span': (45, 48)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 4,
                                     'lemma': '.',
                                     'misc': '',
                                     'upostag': 'PUNCT',
                                     'xpostag': 'Z'}],
                    'base_span': (48, 49)},
                   {'annotations': [{'feats': OrderedDict([('Polarity', 'Neg')]),
                                     'id': 1,
                                     'lemma': 'ei',
                                     'misc': '',
                                     'upostag': 'AUX',
                                     'xpostag': 'V'}],
                    'base_span': (50, 52)},
                   {'annotations': [{'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Ind'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Connegative', 'Yes')]),
                                     'id': 2,
                                     'lemma': 'elatama',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'},
                                    {'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Imp'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Number', 'Sing'),
                                                           ('Person', '2')]),
                                     'id': 2,
                                     'lemma': 'elatama',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'},
                                    {'feats': OrderedDict([('Voice', 'Act'),
                                                           ('Tense', 'Pres'),
                                                           ('Mood', 'Imp'),
                                                           ('VerbForm', 'Fin'),
                                                           ('Number', 'Sing'),
                                                           ('Person', '2'),
                                                           ('Connegative', 'Yes')]),
                                     'id': 2,
                                     'lemma': 'elatama',
                                     'misc': '',
                                     'upostag': 'VERB',
                                     'xpostag': 'V'}],
                    'base_span': (53, 58)},
                   {'annotations': [{'feats': OrderedDict(),
                                     'id': 3,
                                     'lemma': '.',
                                     'misc': '',
                                     'upostag': 'PUNCT',
                                     'xpostag': 'Z'}],
                    'base_span': (58, 59)}]}
    
    assert expected_ud_morph_layer_dict == layer_to_dict( text['ud_morph_analysis'] )
    
    #from pprint import pprint
    #pprint( layer_to_dict(text['ud_morph_analysis']) )