from estnltk_neural.taggers.embeddings.bert.bert_tagger import BertTagger
from estnltk_neural.taggers.neural_morph.new_neural_morph.neural_morph_tagger import SoftmaxEmbTagSumTagger
from estnltk_neural.taggers.neural_morph.new_neural_morph.neural_morph_tagger import SoftmaxEmbCatSumTagger
from estnltk_neural.taggers.neural_morph.new_neural_morph.neural_morph_tagger import Seq2SeqEmbTagSumTagger
from estnltk_neural.taggers.neural_morph.new_neural_morph.neural_morph_tagger import Seq2SeqEmbCatSumTagger
from estnltk_neural.taggers.syntax.stanza_tagger.ensemble_tagger import StanzaSyntaxEnsembleTagger
from estnltk_neural.taggers.syntax.stanza_tagger.stanza_tagger import StanzaSyntaxTagger