{% set data = load_setup_py_data() %}

package:
  name: estnltk_neural
  version: {{ data.get('version')  }}

source:
    path: ../../estnltk_neural

build:
 noarch: python
 number: 0

requirements:
  build:
    - python 
    - estnltk_core >=1.7.4
    - estnltk >=1.7.4

  run:
    - python 
    - estnltk_core >=1.7.4
    - estnltk >=1.7.4
    - transformers
    - pytorch
    - stanza
    - packaging

about:
  home: https://github.com/estnltk/estnltk
  license: GPLv2
  summary: 'EstNLTK neural -- linguistic analysis of Estonian based on neural models'