{% set version = "1.7.4" %}

package:
  name: estnltk_neural
  version: {{ version }}

source:
    path: ../../estnltk_neural

build:
 noarch: python
 number: 0
 script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python 
    - estnltk_core >=1.7.4
    - estnltk >=1.7.4
    - transformers
    - pytorch
    - stanza
    - packaging

about:
  home: https://github.com/estnltk/estnltk
  license: 'Dual License: GPL-2.0 OR Apache-2.0'
  summary: 'EstNLTK neural -- linguistic analysis of Estonian based on neural models'