from .consecutive import iterate_consecutive_spans
from .consecutive import iterate_touching_spans
from .consecutive import iterate_starting_spans
from .consecutive import iterate_ending_spans
from .intersections import iterate_intersecting_spans
from .intersections import iterate_nested_spans
from .intersections import iterate_overlapping_spans