# this test file is automatically generated by tagger_test_maker.py

from estnltk.converters import import_dict
from estnltk.taggers import AddressPartTagger

tagger = AddressPartTagger()

input_text_dict = \
{'layers': [{'_base': 'words',
             'ambiguous': False,
             'attributes': ('normalized_form',),
             'enveloping': None,
             'name': 'words',
             'parent': None,
             'spans': [{'end': 6, 'normalized_form': None, 'start': 0},
                       {'end': 8, 'normalized_form': None, 'start': 7},
                       {'end': 9, 'normalized_form': None, 'start': 8},
                       {'end': 17, 'normalized_form': None, 'start': 10}]}],
 'meta': {},
 'text': 'Rävala 5, Tallinn'}

expected_text_dict = \
{'layers': [{'_base': 'address_parts',
             'ambiguous': True,
             'attributes': ('grammar_symbol', 'type'),
             'enveloping': None,
             'name': 'address_parts',
             'parent': None,
             'spans': [[{'end': 6,
                         'grammar_symbol': 'TÄNAV',
                         'start': 0,
                         'type': 'tänav'},
                        {'end': 6,
                         'grammar_symbol': 'TALU',
                         'start': 0,
                         'type': 'talu'}],
                       [{'end': 8,
                         'grammar_symbol': 'MAJA',
                         'start': 7,
                         'type': None}],
                       [{'end': 17,
                         'grammar_symbol': 'ASULA',
                         'start': 10,
                         'type': 'asula'}]]},
            {'_base': 'words',
             'ambiguous': False,
             'attributes': ('normalized_form',),
             'enveloping': None,
             'name': 'words',
             'parent': None,
             'spans': [{'end': 6, 'normalized_form': None, 'start': 0},
                       {'end': 8, 'normalized_form': None, 'start': 7},
                       {'end': 9, 'normalized_form': None, 'start': 8},
                       {'end': 17, 'normalized_form': None, 'start': 10}]}],
 'meta': {},
 'text': 'Rävala 5, Tallinn'}


expected_layer_text = [['Rävala', 'Rävala'], ['5'], ['Tallinn']]

expected_text = import_dict(expected_text_dict)

input_text = import_dict(input_text_dict)
result = tagger.tag(input_text)
diff = expected_text.diff(result)


def test_basic():
    assert expected_layer_text == result[tagger.output_layer].text, 'AddressTagger test'


def test_complete():
    assert not diff, diff + '\n' + 'AddressTagger test'
