name: Build estnltk conda packages and upload to conda

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_conda.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_conda_packages:
    name: Build estnltk conda package on ${{ matrix.os }} (py ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [windows-latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
        #python-version: ['3.8']
        python-version: ['3.10', '3.11']
        #python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install conda-build and building prerequisites
        run: |
          conda install conda-build conda-verify swig cython
          conda update conda-build

      # Use estnltk-core-channel cache
      # load data from the cache if it exists.
      # this enables to skip the building 
      # step below.
      # Look for the cache key in the workflow 
      # of building estnltk_core conda package
      - name: Cache ec_channel
        id: cache-ec-channel
        uses: actions/cache@v3
        with:
          path: estnltk_core/ec_channel
          key: estnltk-core-channel-2023-08-10-1
          enableCrossOsArchive: true

      - name: Build estnltk_core conda package
        if: steps.cache-ec-channel.outputs.cache-hit != 'true'
        run: |
          cd estnltk_core
          conda build -c conda-forge --output-folder ec_channel conda_recipe
          echo --------------------- 

      - if: matrix.os == 'windows-latest'
        name: Configure Dev Command Prompt for MS Visual C++ (windows-only)
        # https://github.com/ilammy/msvc-dev-cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - if: matrix.os == 'windows-latest'
        name: Build estnltk conda package (windows)
        run: |
          conda build -c conda-forge -c estnltk_core/ec_channel --output-folder estnltk/e_channel estnltk/conda-recipe/windows
          echo --------------------- 
          dir estnltk\e_channel
          echo --------------------- 

      # Use estnltk-channel cache on Ubuntu. 
      # The goal is to store the channel data, so 
      # that it can be used to speed up the building 
      # process of estnltk-neural conda package.
      # Note that if the cache exists, conda build 
      # will overwrite the data, but it is not stored 
      # in cache unless the cache key has been changed.
      # (so, you should change the key if you want 
      #  to store a new build)
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        name: Cache e_channel
        id: cache-e-channel
        uses: actions/cache@v3
        with:
          path: estnltk/e_channel
          key: estnltk-channel-2023-08-10-1
          enableCrossOsArchive: true

      - if: matrix.os != 'windows-latest'
        name: Build estnltk conda package (linux or macos)
        run: |
          conda build -c conda-forge -c estnltk_core/ec_channel --output-folder estnltk/e_channel estnltk/conda-recipe/linux_and_osx
          echo --------------------- 
          ls estnltk/e_channel
          echo --------------------- 

      - uses: actions/upload-artifact@v3
        with:
          name: estnltk-conda-packages
          path: |
            ./estnltk/e_channel/win-64/*.tar.bz2
            ./estnltk/e_channel/linux-64/*.tar.bz2
            ./estnltk/e_channel/osx-64/*.tar.bz2
          retention-days: 14

  upload_to_conda:
    name: Upload estnltk packages to conda
    needs: [build_estnltk_conda_packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: estnltk-conda-packages
          path: conda-packages

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: '3.10'
          conda-channels: anaconda, conda-forge

      - name: Install anaconda-client
        run: |
          conda install anaconda-client

      - name: Upload estnltk conda packages
        run: |
          cd conda-packages
          echo --------------------- 
          ls -lah linux-64
          ls -lah osx-64
          ls -lah win-64
          echo --------------------- 
          linux_packages=$(ls -1 linux-64/*.tar.bz2)
          win_packages=$(ls -1 win-64/*.tar.bz2)
          osx_packages=$(ls -1 osx-64/*.tar.bz2)
          anaconda -t ${{ secrets.conda_upload_token }} upload -l dev --force -u estnltk $linux_packages $win_packages $osx_packages