name: Upload some estnltk packages to conda

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_conda_upload_test.yml'
      
  # Manual run (works only in the default branch) 
  #workflow_dispatch:


jobs:

  upload_to_conda:
    name: Upload estnltk packages to conda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: estnltk-conda-packages
          pattern: estnltk-conda-packages-*
          merge-multiple: true

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: anaconda, conda-forge
          miniconda-version: "latest"
          activate-environment: building

      - name: Install anaconda-client
        shell: bash -el {0}
        run: |
          conda install anaconda-client

      # (!) Important: with "macos-latest", the package path will be "osx-arm64/*.tar.bz2"
      - name: Upload estnltk conda packages
        shell: bash -el {0}
        run: |
          cd estnltk-conda-packages
          echo --------------------- 
          ls -lah win-64
          ls -lah linux-64
          echo --------------------- 
          linux_packages=$(ls -1 linux-64/estnltk-*)
          win_packages=$(ls -1 win-64/estnltk-*)
          anaconda -t ${{ secrets.conda_upload_token }} upload -l dev --force -u estnltk $linux_packages $win_packages