name: Build estnltk_core conda package (and upload to conda later)

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/estnltk_core_conda.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_core_conda_package:
    name: Build estnltk_core conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge

      - name: Install conda-build and conda-verify
        run: |
          conda install conda-build conda-verify

      - name: Build estntlk_core conda package
        run: |
          cd estnltk_core
          conda build -c conda-forge --output-folder . conda_recipe
          echo --- estntlk_core completed --- 
          dir .
          echo --- dir completed ---

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./estnltk_core/noarch/*.tar.bz2
