name: Build estnltk_core conda package and upload to conda

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_core_conda.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_core_conda_package:
    name: Build estnltk_core conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: anaconda, conda-forge
          miniconda-version: "latest"
          activate-environment: building

      - name: Install conda-build and conda-verify
        run: |
          conda install conda-build conda-verify
          conda update conda-build

      # Use estnltk-core-channel cache. 
      # The goal is to store the channel data, so 
      # that it can be used to speed up the building 
      # process of estnltk conda package.
      # Note that if the cache exists, conda build 
      # will overwrite the data, but it is not stored 
      # in cache unless the cache key has been changed.
      # (so, you should change the key if you want 
      #  to store a new build)
      - name: Cache ec_channel
        id: cache-ec-channel
        uses: actions/cache@v4
        with:
          path: estnltk_core/ec_channel
          key: estnltk-core-channel-2024-06-13-1
          enableCrossOsArchive: true

      - name: Build estntlk_core conda package
        run: |
          cd estnltk_core
          conda build -c conda-forge --output-folder ec_channel conda_recipe
          echo --- estntlk_core completed --- 
          dir ec_channel
          echo --- dir completed --- 

      - uses: actions/upload-artifact@v4
        with:
          name: estnltk-core-conda-package
          path: |
            ./estnltk_core/ec_channel/noarch/*.tar.bz2
          retention-days: 14
          overwrite: true


  upload_to_conda:
    name: Upload estnltk_core package to conda
    needs: [build_estnltk_core_conda_package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: estnltk-core-conda-package
          path: conda-packages

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: anaconda, conda-forge
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""

      - name: Install anaconda-client
        run: |
          conda install anaconda-client

      - name: Upload estnltk_core conda package
        run: |
          echo --------------------- 
          cd conda-packages
          echo --------------------- 
          ls -lah
          echo --------------------- 
          packagefile=$(ls -1 *.tar.bz2) 
          echo --------------------- 
          anaconda -t ${{ secrets.conda_upload_token }} upload -l dev --force -u estnltk $packagefile