name: Build estnltk_core conda package (and upload to conda later)

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/estnltk_core_conda.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_core_conda_package:
    name: Build estnltk_core conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Update conda
        run: |
          conda update conda

      - name: Create environment and install conda-build 
        run: |
          conda create -n conda_build python=3.9
          conda activate conda_build
          conda install conda-build conda-verify

      - name: Build estntlk_core conda pckge
        run: |
          conda activate conda_build
          cd ./estnltk_core/conda-recipe
          conda build -c conda-forge  .
          conda build --output conda-recipe
          

      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: |
      #      ./estnltk_core/dist/*.whl
      #      ./estnltk_core/dist/*.tar.gz
