name: Build estnltk conda package (and upload to conda later)

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/estnltk_conda.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_conda_packages:
    name: Build estnltk conda package on ${{ matrix.os }} (py ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        #os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8']
        #python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install conda-build and building prerequisites
        run: |
          conda install conda-build conda-verify swig cython

      # A fix from here: https://github.com/actions/cache/issues/591 
      - name: "Use GNU tar instead BSD tar (fix for windows caching)"
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      # Use estnltk-core-channel cache
      # load data from the cache if it exists.
      # this enables to skip the building 
      # step below.
      # Look for the cache key in the workflow 
      # of building estnltk_core conda package
      - name: Cache ec_channel
        id: cache-ec-channel
        uses: actions/cache@v2
        with:
          path: estnltk_core/ec_channel
          key: estnltk-core-channel-2022-03-18

      - name: Build estnltk_core conda package
        if: steps.cache-ec-channel.outputs.cache-hit != 'true'
        run: |
          cd estnltk_core
          conda build -c conda-forge --output-folder ec_channel conda_recipe
          echo --------------------- 

      - if: matrix.os == 'windows-latest'
        name: Configure Dev Command Prompt for MS Visual C++ (windows-only)
        # https://github.com/ilammy/msvc-dev-cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - if: matrix.os == 'windows-latest'
        name: Build estnltk conda package (windows)
        run: |
          conda build -c conda-forge -c estnltk_core/ec_channel --output-folder estnltk/e_channel estnltk/conda-recipe/windows
          echo --------------------- 
          dir estnltk\e_channel
          echo --------------------- 

      # Use estnltk-channel cache on Ubuntu. 
      # The goal is to store the channel data, so 
      # that it can be used to speed up the building 
      # process of estnltk-neural conda package.
      # Note that if the cache exists, conda build 
      # will overwrite the data, but it is not stored 
      # in cache unless the cache key has been changed.
      # (so, you should change the key if you want 
      #  to store a new build)
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
        name: Cache e_channel
        id: cache-e-channel
        uses: actions/cache@v2
        with:
          path: estnltk/e_channel
          key: estnltk-channel-2022-03-18

      - if: matrix.os != 'windows-latest'
        name: Build estnltk conda package (linux or macos)
        run: |
          conda build -c conda-forge -c estnltk_core/ec_channel --output-folder estnltk/e_channel estnltk/conda-recipe/linux_and_osx
          echo --------------------- 
          ls estnltk/e_channel
          echo --------------------- 

      - uses: actions/upload-artifact@v2
        with:
          name: estnltk-conda-packages
          path: |
            ./estnltk/e_channel/win-64/*.tar.bz2
            ./estnltk/e_channel/linux-64/*.tar.bz2
            ./estnltk/e_channel/osx-64/*.tar.bz2


  upload_to_conda:
    name: Upload estnltk packages to conda
    needs: [build_estnltk_conda_packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: estnltk-conda-packages
          path: conda-packages

      - name: Display built estnltk conda packages
        run: |
          cd conda-packages
          echo --------------------- 
          ls -lah
          echo --------------------- 