name: Build estnltk_neural and upload to PyPI

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_neural_pypi.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_neural_and_sdist:
    name: Build estnltk_neural wheels and source distribution on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build estnltk
        uses: pypa/cibuildwheel@v2.22.0
        with:
          package-dir: ./estnltk
          output-dir:  ./estnltk/wheelhouse
        env:
          # Before build:
          # 0) Install legacy versions of dependency packages (only for py39);
          # 1) install estnltk_core, because the package is not yet 
          #    available from the pypi;
          CIBW_BEFORE_BUILD:  >
            cd estnltk_core && 
            pip install . && 
            cd .. &&
            echo --- estntlk_core completed ---

          # List of available platforms: 
          # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip 
          CIBW_BUILD:  cp311-*64
          #CIBW_BUILD:  cp39-*64  cp310-*64  cp311-*64  cp312-*64  cp313-*64

          # Disable building PyPy wheels on all platforms.
          # Enable if you get it working.
          CIBW_SKIP: pp* *arm64 *musllinux_x86_64 *musllinux_aarch64

      - name: Build estnltk_neural wheel
        run: |
          cd estnltk_core
          python setup.py install 
          echo --- estntlk_core completed --- 
          cd ..
          wheelfile=$(ls -1 estnltk/wheelhouse/*.whl) 
          python -m pip install $wheelfile
          echo --- estntlk completed ---
          cd estnltk_neural
          python -m build --wheel --sdist --outdir dist/ .
          echo --- estntlk_neural completed --- 
          ls dist
          echo --- ls dist completed --- 

      - uses: actions/upload-artifact@v4
        with:
          name: estnltk-neural-pypi-packages
          path: |
            ./estnltk_neural/dist/*.whl
            ./estnltk_neural/dist/*.tar.gz
          retention-days: 14
          overwrite: true

  upload_pypi:
    name: Push to PyPI
    needs: [build_estnltk_neural_and_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: estnltk-neural-pypi-packages
          pattern: estnltk-neural-pypi-packages
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          # Use https://test.pypi.org instead of the default pypi:
          #repository-url: https://test.pypi.org/legacy/
          packages-dir: estnltk-neural-pypi-packages