name: Build estnltk_core and upload to PyPI

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_core_pypi.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  build_estnltk_core_wheels_and_sdist:
    name: Build estnltk_core wheels and source distribution on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build pure-Python wheels & sdict
        run: |
          cd estnltk_core
          python -m build --sdist --wheel --outdir dist/ .
          ls dist

      - uses: actions/upload-artifact@v4
        with:
          path: |
            ./estnltk_core/dist/*.whl
            ./estnltk_core/dist/*.tar.gz
          retention-days: 14
          overwrite: true

  upload_pypi:
    name: Push to PyPI
    needs: [build_estnltk_core_wheels_and_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          # Use https://test.pypi.org instead of the default pypi:
          #repository-url: https://test.pypi.org/legacy/