name: Upload estnltk_core conda package to conda

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_core_conda_upload.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  upload_to_conda:
    name: Upload estnltk_core package to conda
    runs-on: ubuntu-latest
    steps:
      # Use estnltk-core-channel cache. 
      # The goal is to store the channel data, so 
      # that it can be used to speed up the building 
      # process of estnltk conda package.
      # Note that if the cache exists, conda build 
      # will overwrite the data, but it is not stored 
      # in cache unless the cache key has been changed.
      # (so, you should change the key if you want 
      #  to store a new build)
      - name: Cache ec_channel
        id: cache-ec-channel
        uses: actions/cache@v4
        with:
          path: estnltk_core/ec_channel
          key: estnltk-core-channel-2024-06-13-1
          enableCrossOsArchive: true

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          auto-update-conda: true
          python-version: "3.10"
          channels: anaconda, conda-forge
          miniconda-version: "latest"

      - name: Install anaconda-client
        shell: bash -l {0}
        run: |
          conda install anaconda-client

      - name: Upload estnltk_core conda package
        shell: bash -l {0}
        run: |
          echo --------------------- 
          cd estnltk_core/ec_channel/noarch
          echo --------------------- 
          ls -lah
          echo --------------------- 
          packagefile=$(ls -1 *.tar.bz2) 
          echo --------------------- 
          conda list anaconda
          echo --------------------- 
          anaconda -t ${{ secrets.conda_upload_token }} upload -l dev --force -u estnltk $packagefile