name: Build estnltk_core (and upload to PyPI later)

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/estnltk_core_pypi.yml'
      
  # Manual run (works only in the default branch)
  workflow_dispatch:


jobs:
  build_estnltk_core_wheels_and_sdist:
    name: Build estnltk_core wheels and source distribution on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build pure-Python wheels & sdict
        run: |
          cd estnltk_core
          python -m build --sdist --wheel --outdir dist/ .
          ls dist

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz
          
