name: Upload estnltk linux_aarch64 to PyPI

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/estnltk_pypi_linux_aarch64_upload.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  upload_pypi:
    name: Push to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: estnltk-pypi-packages-linux-aarch64-
          pattern: estnltk-pypi-packages-linux-aarch64-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          packages-dir: estnltk-pypi-packages
          # Use https://test.pypi.org instead of the default pypi:
          #repository-url: https://test.pypi.org/legacy/