name: Test gh actions caching 2

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/test_gh_actions_cache.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:


jobs:
  test_creating_cache:
    name: Create cache
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      #- name: Create empty cache folder
      #  run: |
      #    cd estnltk_core
      #    mkdir ec_channel

      - name: Cache ec-channel
        id: cache-ec-channel
        uses: actions/cache@v2
        with:
          path: estnltk_core/ec_channel
          key: ${{ runner.os }}-ec-channel

      - name: Display ec-channel cache (1)
        run: |
          cd estnltk_core
          echo -----------------------
          cd ec_channel
          ls -lah
          echo -----------------------

      - name: Create content for caching
        #if: steps.cache-ec-channel.outputs.cache-hit != 'true'
        run: |
          echo Creating content for caching!
          cd estnltk_core
          cd ec_channel
          touch file1.txt
          echo ' Hello!' >> file1.txt
          touch file2.txt
          mkdir -p subdir1
          mkdir -p subdir2
          cd subdir1
          touch subdir1_file1.txt
          touch subdir1_file2.txt
          echo ' Hello-hello!' >> subdir1_file2.txt

      - name: Display ec-channel cache (2)
        run: |
          cd estnltk_core
          echo -----------------------
          ls -lah
          echo -----------------------
          cd ec_channel
          ls -lah
          echo -----------------------
          cd subdir2
          ls -lah
          echo -----------------------
          cd ..
          cd subdir1
          ls -lah
          echo -----------------------
          cat subdir1_file2.txt
          echo -----------------------