name: Test use existing gh actions cache

on: 
  push:
    branches:
      - devel_1.6_split
    paths:
      - '.github/workflows/test_use_gh_actions_cache.yml'
      
  # Manual run (works only in the default branch)
  #workflow_dispatch:
  

jobs:
  test_using_cache:
    name: Use cache
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Create empty cache folder
        run: |
          cd estnltk_core
          mkdir ec_channel

      - name: Cache ec-channel
        id: cache-ec-channel
        uses: actions/cache@v2
        with:
          path: estnltk_core/ec_channel
          key: ${{ runner.os }}-ec-channel
        # Cache restored from key: Linux-ec-channel

      - name: Display ec-channel cache
        run: |
          cd estnltk_core
          echo -----------------------
          ls -lah
          echo -----------------------
          cd ec_channel
          ls -lah
          echo -----------------------
          cd subdir2
          ls -lah
          echo -----------------------
          cd ..
          cd subdir1
          ls -lah
          echo -----------------------
          cat subdir1_file2.txt
          echo -----------------------